#!/bin/bash

PGNAME="tec-arch"
VERSION="v0.0.1"
COMMAND=
TASKDIR=
ENVNAME=
DESKNAME=
TASKNAME=
ISDEBUG=false

# Colors
COLOR_BGRN='\033[1;32m'
COLOR_BMAG='\033[1;35m'
COLOR_BWHT='\033[1;37m'
COLOR_OFF='\033[0m'


function die() {
	echo "$PGNAME:" "$@" >&2
	exit 1
}

function usage()
{
cat << EOF
Usage: tec ${PGNAME/tec-/} [OPTION]... [TASKID]...
    arch        archive task directory
    ex          extract task directory
    help        show this help message and exit
    ls          list archived tasks
EOF
}
function check_arg_env()
{
    if [ -z "$ENVNAME" ]; then
        die "no environment name is passed"
    elif [ ! -d "$TASKDIR/$ENVNAME" ]; then
        die "'$ENVNAME': no such environment name"
    fi
}

function check_arg_desk()
{
    if [ -z "$DESKNAME" ]; then
        die "no desk name is passed"
    elif [ ! -d "$TASKDIR/$ENVNAME/$DESKNAME" ]; then
        die "'$DESKNAME': no such desk name"
    fi
}

function check_arg_task()
{
    if [ -z "$TASKNAME" ]; then
        die "no task ID is passed"
    elif [ ! -d "$TASKDIR/$ENVNAME/$DESKNAME/$TASKNAME" ]; then
        die "'$TASKNAME': no such task ID"
    fi
}

function get_and_check_env()
{
    local curr=
    local fname="$TASKDIR/.tec/toggles"

    if [ -f "$fname" ]; then
        curr="$(grep -i curr "$fname" | cut -f 2 -d ':' | tr -d ' ')"
    fi

    if [ -z "$ENVNAME" ]; then
        ENVNAME="$curr"
    fi

    # check environment name
    if [ -z "$ENVNAME" ]; then
        die "no environment name is passed"
    elif [ ! -d "$TASKDIR/$ENVNAME" ]; then
        die "'$ENVNAME': no such environment name"
    fi
}

function get_and_check_desk()
{
    local curr=
    local fname="$TASKDIR/$ENVNAME/.tec/toggles"

    if [ -f "$fname" ]; then
        curr="$(grep -i curr "$fname" | cut -f 2 -d ':' | tr -d ' ')"
    fi

    if [ -z "$DESKNAME" ]; then
        DESKNAME="$curr"
    fi

    # check environment name
    if [ -z "$DESKNAME" ]; then
        die "no desk name is passed"
    elif [ ! -d "$TASKDIR/$ENVNAME/$DESKNAME" ]; then
        die "'$DESKNAME': no such desk name"
    fi
}

function get_and_check_task()
{
    local curr=
    local fname="$TASKDIR/$ENVNAME/$DESKNAME/.tec/toggles"

    if [ -f "$fname" ]; then
        curr="$(grep -i curr "$fname" | cut -f 2 -d ':' | tr -d ' ')"
    fi

    if [ -z "$TASKNAME" ]; then
        TASKNAME="$curr"
    fi

    # check environment name
    if [ -z "$TASKNAME" ]; then
        die "no task ID is passed"
    elif [ ! -d "$TASKDIR/$ENVNAME/$DESKNAME/$TASKNAME" ]; then
        die "'$TASKNAME': no such task ID"
    fi
}

function _arch_check_args()
{
    get_and_check_env
    get_and_check_desk
    get_and_check_task
}


function arch_arch()
{
    local uwd="$TASKDIR/$ENVNAME/$DESKNAME"
    local src="$TASKNAME"
    local dst="$TASKNAME.tar"

    if [ -n "$1" ]; then
        TASKNAME="$1"
        src="$TASKNAME"
        dst="$TASKNAME.tar"
    fi

    if grep -q "$src" "$uwd/.tec/toggles"; then
        die "'$TASKNAME': cannot archive toggle task"
    elif [ ! -d "$uwd/$TASKNAME" ]; then
        die "'$TASKNAME': no such task ID"
    fi

    cd "$uwd" || die "could not switch to directory '$uwd'"
    if ! tar -cf "$dst" "$src"; then
        die "could not create archive '$?'"
    fi
    rm -rf "$src"
}

function arch_ex()
{
    local uwd="$TASKDIR/$ENVNAME/$DESKNAME"
    local src="${TASKNAME}.tar"

    if [ -n "$1" ]; then
        TASKNAME="$1"
        src="${TASKNAME}.tar"
        dst="${TASKNAME}"
    fi

    if [ ! -f "$uwd/$src" ]; then
        die "'$src': no such archived task"
    fi

    cd "$uwd" || die "could not switch to directory '$uwd'"
    if ! tar -xf "$src"; then
        die "could not extract archive '$?'"
    fi
    rm -rf "$src"
}

function arch_help()
{
    usage
}

function arch_ls()
{
    local uwd="$TASKDIR/$ENVNAME/$DESKNAME"

    find "$uwd" -name '*.tar' | while read -r arch; do
        local mark="arch"
        local taskid="$(basename -s .tar "$arch")"
        local mydesc="$(tar -xOf "$uwd/$taskid.tar" "$taskid/.tec/units" | grep desc | cut -f 2 -d ':')"

        # HOTFIX: Trim leading whitespace in description
        mydesc="${mydesc#${mydesc%%[![:space:]]*}}"
        printf "${COLOR_BGRN}%s${COLOR_OFF} ${COLOR_BMAG}%-10s${COLOR_OFF} ${COLOR_BWHT}%s${COLOR_OFF}\n" "$mark" "$taskid" "$mydesc"
    done
}


# Driver part of the code
OPTS=$(getopt -o d:e:i:DP:T:hV --long desk:,env:debug,,taskid:,pgndir:,taskdir:help,version -n "$PGNAME" -- "$@")
if [ $? -ne 0 ]; then
    #echo "error parsing options" >&2
    exit 1
fi

## Reset the positional parameters to the parsed options
eval set -- "$OPTS"

while true; do
    case "$1" in
        -d)
            DESKNAME="$2"
            shift 2
            ;;
        -e)
            ENVNAME="$2"
            shift 2
            ;;
        -i)
            TASKNAME="$2"
            shift 2
            ;;
        -P)
            PGNDIRBASE="$2"
            shift 2
            ;;
        -T)
            TASKDIR="$2"
            shift 2
            ;;
        -V)
            echo "$PGNAME: $VERSION"
            exit 0
            ;;
        --)
            shift
            break
            ;;
        *)
            elog "invalid option '$1'"
            exit 1
    esac
done

# TODO: add default command (maybe)
COMMAND="$1"; shift

_arch_check_args


if [ ! -t 1 ]; then
    COLOR_BGRN=''
    COLOR_BMAG=''
    COLOR_BWHT=''
    COLOR_OFF=''
fi

if [ "$COMMAND" = "arch" ]; then
    arch_arch "$@"
elif [ "$COMMAND" = "ex" ]; then
    arch_ex "$@"
elif [ -z "$COMMAND" ] || [ "$COMMAND" = "ls" ]; then
    arch_ls "$@"
elif [ "$COMMAND" = "help" ]; then
    arch_help "$@"
else
    die "'$COMMAND': no such command"
fi
