#!/bin/bash

PGNAME="tec-arch"
VERSION="v0.0.1"
COMMAND=
TASKDIR=
ENVNAME=
DESKNAME=
TASKNAME=
ISDEBUG=false

# Colors
COLOR_BGRN='\033[1;32m'
COLOR_BMAG='\033[1;35m'
COLOR_BWHT='\033[1;37m'
COLOR_OFF='\033[0m'


function die() {
	echo "$PGNAME:" "$@" >&2
	exit 1
}

function usage()
{
cat << EOF
Usage: tec ${PGNAME/tec-/} [OPTION]...
    arch        archive task directory
    extract     extract task directory
    help        show this help message and exit
    list        list archived tasks
EOF
}
function check_arg_prj()
{
    if [ -z "$ENVNAME" ]; then
        die "no environment name is passed"
    elif [ ! -d "$TASKDIR/$ENVNAME" ]; then
        die "'$ENVNAME': no such environment name"
    fi
}

function check_arg_brd()
{
    if [ -z "$DESKNAME" ]; then
        die "no desk name is passed"
    elif [ ! -d "$TASKDIR/$ENVNAME/$DESKNAME" ]; then
        die "'$DESKNAME': no such desk name"
    fi
}

function check_arg_task()
{
    if [ -z "$TASKNAME" ]; then
        die "no task ID is passed"
    elif [ ! -d "$TASKDIR/$ENVNAME/$DESKNAME/$TASKNAME" ]; then
        die "'$TASKNAME': no such task ID"
    fi
}

function get_and_check_project()
{
    local curr=
    local fname="$TASKDIR/.tec/toggles"

    if [ -f "$fname" ]; then
        curr="$(grep -i curr "$fname" | cut -f 2 -d '=' | tr -d ' ')"
    fi

    if [ -z "$PRJNAME" ]; then
        PRJNAME="$curr"
    fi

    # check project name
    if [ -z "$PRJNAME" ]; then
        die "no project name is passed"
    elif [ ! -d "$TASKDIR/$PRJNAME" ]; then
        die "'$PRJNAME': no such project name"
    fi
}

function get_and_check_board()
{
    local curr=
    local fname="$TASKDIR/$PRJNAME/.tec/toggles"

    if [ -f "$fname" ]; then
        curr="$(grep -i curr "$fname" | cut -f 2 -d '=' | tr -d ' ')"
    fi

    if [ -z "$BRDNAME" ]; then
        BRDNAME="$curr"
    fi

    # check project name
    if [ -z "$BRDNAME" ]; then
        die "no board name is passed"
    elif [ ! -d "$TASKDIR/$PRJNAME/$BRDNAME" ]; then
        die "'$BRDNAME': no such board name"
    fi
}

function get_and_check_task()
{
    local curr=
    local fname="$TASKDIR/$PRJNAME/$BRDNAME/.tec/toggles"

    if [ -f "$fname" ]; then
        curr="$(grep -i curr "$fname" | cut -f 2 -d '=' | tr -d ' ')"
    fi

    if [ -z "$TASKNAME" ]; then
        TASKNAME="$curr"
    fi

    # check project name
    if [ -z "$TASKNAME" ]; then
        die "no task ID is passed"
    elif [ ! -d "$TASKDIR/$PRJNAME/$BRDNAME/$TASKNAME" ]; then
        die "'$TASKNAME': no such task ID"
    fi
}

function _arch_check_args()
{
    get_and_check_project
    get_and_check_board
    get_and_check_task
}


function arch_arch()
{
    local uwd="$TASKDIR/$ENVNAME/$DESKNAME"
    local src="$TASKNAME"
    local dst="$TASKNAME.tar"

    # Add check to archive only done tasks
    if ! grep -q "name : done" "$uwd/$src/.tec/column"; then
        die "'$TASKNAME': cannot archive non-done task"
    fi

    cd "$uwd" || die "could not switch to directory '$uwd'"
    if ! tar -cf "$dst" "$src"; then
        die "could not create archive '$?'"
    fi
    rm -rf "$src"
}

function arch_extract()
{
    local uwd="$TASKDIR/$ENVNAME/$DESKNAME"
    local src="${TASKNAME}.tar"

    if [ ! -f "$uwd/$src" ]; then
        die "'$src': no such archived task"
    fi

    cd "$uwd" || die "could not switch to directory '$uwd'"
    if ! tar -xf "$src"; then
        die "could not extract archive '$?'"
    fi
    rm -rf "$src"
}

function arch_help()
{
    usage
}

function arch_list()
{
    local uwd="$TASKDIR/$ENVNAME/$DESKNAME"
    find "$uwd" -name '*.tar' | while read -r arch; do
        local mark="arch"
        local taskid="$(basename -s .tar "$arch")"
        local mydesc="$(tar -xOf "$uwd/$taskid.tar" "$taskid/.tec/units" | grep desc | cut -f 2 -d ':')"

        # HOTFIX: Trim leading whitespace in description
        mydesc="${mydesc#${mydesc%%[![:space:]]*}}"
        printf "${COLOR_BGRN}%s${COLOR_OFF} ${COLOR_BMAG}%-10s${COLOR_OFF} ${COLOR_BWHT}%s${COLOR_OFF}\n" "$mark" "$taskid" "$mydesc"
    done
}


# Driver part of the code
OPTS=$(getopt -o d:e:i:P:T:hV --long desk:,env:,taskid:,pgndir:,taskdir:help,version -n "$PGNAME" -- "$@")
if [ $? -ne 0 ]; then
    #echo "error parsing options" >&2
    exit 1
fi

## Reset the positional parameters to the parsed options
eval set -- "$OPTS"

while true; do
    case "$1" in
        -d)
            DESKNAME="$2"
            shift 2
            ;;
        -e)
            ENVNAME="$2"
            shift 2
            ;;
        -i)
            TASKNAME="$2"
            shift 2
            ;;
        -P)
            PGNDIRBASE="$2"
            shift 2
            ;;
        -T)
            TASKDIR="$2"
            shift 2
            ;;
        -V)
            echo "$PGNAME: $VERSION"
            exit 0
            ;;
        --)
            shift
            break
            ;;
        *)
            elog "invalid option '$1'"
            exit 1
    esac
done

# TODO: add default command (maybe)
COMMAND="$1"; shift

_arch_check_args


if [ ! -t 1 ]; then
    COLOR_BGRN=''
    COLOR_BMAG=''
    COLOR_BWHT=''
    COLOR_OFF=''
fi

if [ "$COMMAND" = "arch" ]; then
    arch_arch "$@"
elif [ "$COMMAND" = "extract" ]; then
    arch_extract "$@"
elif [ -z "$COMMAND" ] || [ "$COMMAND" = "list" ]; then
    arch_list "$@"
elif [ "$COMMAND" = "help" ]; then
    arch_help "$@"
else
    die "'$COMMAND': no such command"
fi
